name: Mi workflow

on: push

jobs:
  tareas:
    runs-on: ubuntu-latest
    permissions:
       security-events: write
    steps:
      - name: scaneo
        uses: advanced-security/python-lint-code-scanning-action@v1
        with:
          linter: pylint
          
        
